/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import StartProgram.LogIn;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rusla
 */
public class employeemenu extends javax.swing.JFrame {

    /**
     * Creates new form employeemenu
     */
    public employeemenu() {
        initComponents();
    }
    
    public employeemenu(String empid) {
        initComponents();
        EMPID.setText(empid);
        employeeprofile.setVisible(true);
        acceptorderpanel.setVisible(false);
        pendingorderpanel.setVisible(false);
        completedorder.setVisible(false);
               try{
            
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            Statement statement = connection.createStatement();
            int EmpID= Integer.parseInt(EMPID.getText());
       
        
            String sql5 = "Select * from employee where employeeid='"+EmpID+"'";
            ResultSet row = statement.executeQuery(sql5);
            
            if(row.next()){
               
               String empName = row.getString("employeename");
               jTextField16.setText(empName);
               
               
            }  
                
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainsidepanelemployee = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        empcompletedorderbtn = new javax.swing.JButton();
        employeeprofilebtn = new javax.swing.JButton();
        empacceptorderbtn = new javax.swing.JButton();
        emppendingorderbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        changeablemenuemployee = new javax.swing.JPanel();
        employeeprofile = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EMPID = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        acceptorderpanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Accbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        allorderstable = new javax.swing.JScrollPane();
        allordertable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        pendingorderpanel = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        allostatcombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        oidlabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        allorderstable1 = new javax.swing.JScrollPane();
        pendingtable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabell = new javax.swing.JLabel();
        completedorder = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        allorderstable3 = new javax.swing.JScrollPane();
        allordertable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainsidepanelemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(204, 204, 204));
        jButton17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(204, 102, 0));
        jButton17.setText("Log Out");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 760, -1, 40));

        empcompletedorderbtn.setBackground(new java.awt.Color(0, 0, 0));
        empcompletedorderbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empcompletedorderbtn.setForeground(new java.awt.Color(255, 255, 255));
        empcompletedorderbtn.setText("COMPLETED ORDER");
        empcompletedorderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        empcompletedorderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empcompletedorderbtnMouseClicked(evt);
            }
        });
        empcompletedorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcompletedorderbtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(empcompletedorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 230, 50));

        employeeprofilebtn.setBackground(new java.awt.Color(0, 0, 0));
        employeeprofilebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        employeeprofilebtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeprofilebtn.setText("PROFILE");
        employeeprofilebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        employeeprofilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeprofilebtnMouseClicked(evt);
            }
        });
        employeeprofilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeprofilebtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(employeeprofilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 50));

        empacceptorderbtn.setBackground(new java.awt.Color(0, 0, 0));
        empacceptorderbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empacceptorderbtn.setForeground(new java.awt.Color(255, 255, 255));
        empacceptorderbtn.setText("ORDER REQUESTS");
        empacceptorderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        empacceptorderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empacceptorderbtnMouseClicked(evt);
            }
        });
        empacceptorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empacceptorderbtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(empacceptorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 230, 50));

        emppendingorderbtn.setBackground(new java.awt.Color(0, 0, 0));
        emppendingorderbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emppendingorderbtn.setForeground(new java.awt.Color(255, 255, 255));
        emppendingorderbtn.setText("PENDING ORDER");
        emppendingorderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        emppendingorderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emppendingorderbtnMouseClicked(evt);
            }
        });
        emppendingorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emppendingorderbtnActionPerformed(evt);
            }
        });
        mainsidepanelemployee.add(emppendingorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/SidePanel.jpg"))); // NOI18N
        mainsidepanelemployee.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -20, 420, 1050));

        getContentPane().add(mainsidepanelemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 850));

        changeablemenuemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeprofile.setBackground(new java.awt.Color(255, 255, 255));
        employeeprofile.setMinimumSize(new java.awt.Dimension(950, 850));
        employeeprofile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        employeeprofile.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Profile");
        employeeprofile.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAME:");
        employeeprofile.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/employeeicon.png"))); // NOI18N
        employeeprofile.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, 190));

        EMPID.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        EMPID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EMPID.setText("EmployeeID");
        EMPID.setBorder(null);
        EMPID.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        EMPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPIDActionPerformed(evt);
            }
        });
        employeeprofile.add(EMPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 250, 40));

        jTextField16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("Name");
        jTextField16.setBorder(null);
        jTextField16.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        employeeprofile.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 250, 40));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 51, 0));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        employeeprofile.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        changeablemenuemployee.add(employeeprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        acceptorderpanel.setBackground(new java.awt.Color(255, 255, 255));
        acceptorderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 51, 0));
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        acceptorderpanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText(":ACCEPT ORDER:");
        acceptorderpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        Accbtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        Accbtn.setForeground(new java.awt.Color(204, 51, 0));
        Accbtn.setText("ACCEPT");
        Accbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccbtnActionPerformed(evt);
            }
        });
        acceptorderpanel.add(Accbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 240, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 51, 0));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        acceptorderpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 170, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OrderId");
        acceptorderpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 120, 20));

        allordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DATE", "TIME", "Order ID", "RECIEVER ADDRESS", "AREA", "PARCEL TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        allordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allordertableMouseClicked(evt);
            }
        });
        allorderstable.setViewportView(allordertable);

        acceptorderpanel.add(allorderstable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 880, 260));
        acceptorderpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1040, 860));

        changeablemenuemployee.add(acceptorderpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        pendingorderpanel.setBackground(new java.awt.Color(255, 255, 255));
        pendingorderpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 51, 0));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pendingorderpanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        allostatcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Processing For Delivery", "picked up", "Reached Hub", "On the way to Delivery", "Completed" }));
        pendingorderpanel.add(allostatcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, -1, 30));

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 51, 0));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pendingorderpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 80, 30));

        oidlabel.setForeground(new java.awt.Color(255, 255, 255));
        oidlabel.setText("jLabel7");
        pendingorderpanel.add(oidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 51, 0));
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pendingorderpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 100, 40));

        pendingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ORDER NO", "DATE", "TIME", "REC NAME", "REC ADRESS", "REC PHONE", "AREA", "Parcel Type", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pendingtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingtableMouseClicked(evt);
            }
        });
        allorderstable1.setViewportView(pendingtable);

        pendingorderpanel.add(allorderstable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 970, 310));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText(":PENDING ORDER:");
        pendingorderpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));
        pendingorderpanel.add(jLabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1030, 860));

        changeablemenuemployee.add(pendingorderpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        completedorder.setBackground(new java.awt.Color(255, 255, 255));
        completedorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 51, 0));
        jButton10.setText("X");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        completedorder.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 33));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText(":COMPLETED ORDER:");
        completedorder.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        completedorder.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1030, 860));

        allordertable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DATE", "TIME", "Order ID", "RECIEVER ADDRESS", "AREA", "PARCEL TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        allordertable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allordertable3MouseClicked(evt);
            }
        });
        allorderstable3.setViewportView(allordertable3);

        completedorder.add(allorderstable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 880, 260));

        changeablemenuemployee.add(completedorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 850));

        getContentPane().add(changeablemenuemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1030, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void employeeprofilebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeprofilebtnMouseClicked
       changeablemenuemployee.setVisible(true);
       acceptorderpanel.setVisible(false);
       employeeprofile.setVisible(true);
       completedorder.setVisible(false);
       pendingorderpanel.setVisible(false);
       
       try{
            
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            Statement statement = connection.createStatement();
            int EmpID= Integer.parseInt(EMPID.getText());
       
        
            String sql5 = "Select * from employee where employeeid='"+EmpID+"'";
            ResultSet row = statement.executeQuery(sql5);
            
            if(row.next()){
               
               String empName = row.getString("employeename");
               jTextField16.setText(empName);
               
               
            }  
                
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_employeeprofilebtnMouseClicked

    private void empacceptorderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empacceptorderbtnMouseClicked
       changeablemenuemployee.setVisible(true);
       acceptorderpanel.setVisible(true);
       employeeprofile.setVisible(false);
       completedorder.setVisible(false);
       pendingorderpanel.setVisible(false);
    }//GEN-LAST:event_empacceptorderbtnMouseClicked

    private void emppendingorderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emppendingorderbtnMouseClicked
          changeablemenuemployee.setVisible(true);
       acceptorderpanel.setVisible(false);
       employeeprofile.setVisible(false);
       completedorder.setVisible(false);
       pendingorderpanel.setVisible(true);
    }//GEN-LAST:event_emppendingorderbtnMouseClicked

    private void empcompletedorderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empcompletedorderbtnMouseClicked
          changeablemenuemployee.setVisible(true);
       acceptorderpanel.setVisible(false);
       employeeprofile.setVisible(false);
       completedorder.setVisible(true);
       pendingorderpanel.setVisible(false);
    }//GEN-LAST:event_empcompletedorderbtnMouseClicked

    private void EMPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMPIDActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void employeeprofilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeprofilebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeprofilebtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void empacceptorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empacceptorderbtnActionPerformed
try{
            DefaultTableModel tbl = (DefaultTableModel)allordertable.getModel();
            tbl.setRowCount(0);    
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            String Status="Processing";
            Statement statement = connection.createStatement();
            
            
            int EmpID= Integer.parseInt(EMPID.getText());
            String sql3 = "Select * from ALLORDERINFO WHERE EmployeeID='"+EmpID+"' AND OrderStatus= '"+Status+"'";
            
            ResultSet row = statement.executeQuery(sql3);
            
            while(row.next()){
               String Orderdate = row.getString("OrderDate");
               String Ordertime = row.getString("OrderTime");
               String OrderID= String.valueOf(row.getInt("OrderId"));
               String RecAddress = row.getString("RecieversAddress");
               String RecArea = row.getString("RecieversArea");
               String Parcel = row.getString("ParcelType");
               String tbdata[] = {Orderdate,Ordertime,OrderID,RecAddress,RecArea,Parcel};
               DefaultTableModel table1 = (DefaultTableModel)allordertable.getModel();
               table1.addRow(tbdata);              
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_empacceptorderbtnActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int response= JOptionPane.showConfirmDialog(this,"Are You Sure You Want to Log Out?","exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            new LogIn().setVisible(true);
            dispose();
        }
        if(response==JOptionPane.NO_OPTION){
            this.setVisible(true);

        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void AccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccbtnActionPerformed
try{
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String user = "asfiqun";
            String pass = "123456";
            Connection conn = DriverManager.getConnection(url,user,pass);
            String status= "Processing For Delivery";
            Statement statement = conn.createStatement();
            String sql ="update ALLORDERINFO set OrderStatus='"+status+"' where OrderId='"+Integer.parseInt(jLabel2.getText())+"'" ;
            int row = statement.executeUpdate(sql);

            JOptionPane.showMessageDialog(null,"Success");
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AccbtnActionPerformed

    private void allordertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allordertableMouseClicked
       DefaultTableModel model = (DefaultTableModel)allordertable.getModel();
       int selectedRowIndex = allordertable.getSelectedRow();
       jLabel2.setText(model.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_allordertableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
            DefaultTableModel tbl = (DefaultTableModel)allordertable.getModel();
            tbl.setRowCount(0);    
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            String Status="Processing";
            Statement statement = connection.createStatement();
            
            
            int EmpID= Integer.parseInt(EMPID.getText());
            String sql3 = "Select * from ALLORDERINFO WHERE EmployeeID='"+EmpID+"' AND OrderStatus= '"+Status+"'";
            
            ResultSet row = statement.executeQuery(sql3);
            
            while(row.next()){
               String Orderdate = row.getString("OrderDate");
               String Ordertime = row.getString("OrderTime");
               String OrderID= String.valueOf(row.getInt("OrderId"));
               String RecAddress = row.getString("RecieversAddress");
               String RecArea = row.getString("RecieversArea");
               String Parcel = row.getString("ParcelType");
               String tbdata[] = {Orderdate,Ordertime,OrderID,RecAddress,RecArea,Parcel};
               DefaultTableModel table1 = (DefaultTableModel)allordertable.getModel();
               table1.addRow(tbdata);              
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void allordertable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allordertable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_allordertable3MouseClicked

    private void empcompletedorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcompletedorderbtnActionPerformed
try{
            DefaultTableModel tbl = (DefaultTableModel)allordertable3.getModel();
            tbl.setRowCount(0);    
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            String Status="Completed";
            Statement statement = connection.createStatement();
            
            
            int EmpID= Integer.parseInt(EMPID.getText());
            String sql3 = "Select * from ALLORDERINFO WHERE EmployeeID='"+EmpID+"' AND OrderStatus= '"+Status+"'";
            
            ResultSet row = statement.executeQuery(sql3);
            
            while(row.next()){
               String Orderdate = row.getString("OrderDate");
               String Ordertime = row.getString("OrderTime");
               String OrderID= String.valueOf(row.getInt("OrderId"));
               String RecAddress = row.getString("RecieversAddress");
               String RecArea = row.getString("RecieversArea");
               String Parcel = row.getString("ParcelType");
               String tbdata[] = {Orderdate,Ordertime,OrderID,RecAddress,RecArea,Parcel};
               DefaultTableModel table1 = (DefaultTableModel)allordertable3.getModel();
               table1.addRow(tbdata);              
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_empcompletedorderbtnActionPerformed

    private void emppendingorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emppendingorderbtnActionPerformed
try{
            DefaultTableModel tbl = (DefaultTableModel)pendingtable.getModel();
            tbl.setRowCount(0);    
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            String Status="Completed";
            Statement statement = connection.createStatement();
            
            
            int EmpID= Integer.parseInt(EMPID.getText());
            String sql3 = "Select * from ALLORDERINFO WHERE EmployeeID='"+EmpID+"' AND OrderStatus!= 'Completed'";
            
            ResultSet row = statement.executeQuery(sql3);
            
            while(row.next()){
               String OrderID= String.valueOf(row.getInt("OrderId"));
               String Orderdate = row.getString("OrderDate");
               String Ordertime = row.getString("OrderTime");
               String RecieversName = row.getString("RecieversName");
               String RecAddress = row.getString("RecieversAddress");
               String RecieversPhone = row.getString("RecieversPhone");
               String RecArea = row.getString("RecieversArea");
               String Parcel = row.getString("ParcelType");
               String OrdStatus= row.getString("OrderStatus");
               String tbdata[] = {OrderID,Orderdate,Ordertime,RecieversName,RecAddress,RecieversPhone,RecArea,Parcel,OrdStatus};
               DefaultTableModel table1 = (DefaultTableModel)pendingtable.getModel();
               table1.addRow(tbdata);              
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_emppendingorderbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String user = "asfiqun";
            String pass = "123456";
            int EmpID= Integer.parseInt(EMPID.getText());
            Connection conn = DriverManager.getConnection(url,user,pass);
            Statement statement = conn.createStatement();
            String sql ="update ALLORDERINFO set OrderStatus='"+allostatcombo.getSelectedItem().toString()+"' WHERE EmployeeID='"+EmpID+"'AND OrderId='"+Integer.parseInt(oidlabel.getText())+"'";
            int row = statement.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null,"Success");
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pendingtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingtableMouseClicked
       DefaultTableModel model = (DefaultTableModel)pendingtable.getModel();
       int selectedRowIndex = pendingtable.getSelectedRow();
       oidlabel.setText(model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_pendingtableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
            DefaultTableModel tbl = (DefaultTableModel)pendingtable.getModel();
            tbl.setRowCount(0);    
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            String Status="Completed";
            Statement statement = connection.createStatement();
            
            
            int EmpID= Integer.parseInt(EMPID.getText());
            String sql3 = "Select * from ALLORDERINFO WHERE EmployeeID='"+EmpID+"' AND OrderStatus!= 'Completed'";
            
            ResultSet row = statement.executeQuery(sql3);
            
            while(row.next()){
               String OrderID= String.valueOf(row.getInt("OrderId"));
               String Orderdate = row.getString("OrderDate");
               String Ordertime = row.getString("OrderTime");
               String RecieversName = row.getString("RecieversName");
               String RecAddress = row.getString("RecieversAddress");
               String RecieversPhone = row.getString("RecieversPhone");
               String RecArea = row.getString("RecieversArea");
               String Parcel = row.getString("ParcelType");
               String OrdStatus= row.getString("OrderStatus");
               String tbdata[] = {OrderID,Orderdate,Ordertime,RecieversName,RecAddress,RecieversPhone,RecArea,Parcel,OrdStatus};
               DefaultTableModel table1 = (DefaultTableModel)pendingtable.getModel();
               table1.addRow(tbdata);              
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeemenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accbtn;
    private javax.swing.JTextField EMPID;
    private javax.swing.JPanel acceptorderpanel;
    private javax.swing.JScrollPane allorderstable;
    private javax.swing.JScrollPane allorderstable1;
    private javax.swing.JScrollPane allorderstable3;
    private javax.swing.JTable allordertable;
    private javax.swing.JTable allordertable3;
    private javax.swing.JComboBox<String> allostatcombo;
    private javax.swing.JPanel changeablemenuemployee;
    private javax.swing.JPanel completedorder;
    private javax.swing.JButton empacceptorderbtn;
    private javax.swing.JButton empcompletedorderbtn;
    private javax.swing.JPanel employeeprofile;
    private javax.swing.JButton employeeprofilebtn;
    private javax.swing.JButton emppendingorderbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabell;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JPanel mainsidepanelemployee;
    private javax.swing.JLabel oidlabel;
    private javax.swing.JPanel pendingorderpanel;
    private javax.swing.JTable pendingtable;
    // End of variables declaration//GEN-END:variables
}
