package StartProgram;

import Admin.adminmenu2;
import Customer.MainclassCustomer;
import Employee.employeemenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        RegisterPage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LoginEmail = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        LoginPassword = new javax.swing.JPasswordField();
        LogInbtn = new javax.swing.JButton();
        ExitLogin = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        UserType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1150, 650));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(480, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(32, 32, 32));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 20, -1));

        RegisterPage.setBackground(new java.awt.Color(0, 0, 0));
        RegisterPage.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        RegisterPage.setForeground(new java.awt.Color(223, 112, 0));
        RegisterPage.setText("Sign Up");
        RegisterPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPageActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 130, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logInBG.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 650));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(520, 650));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(223, 112, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(420, 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 420, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 112, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Welcome Back!");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 310, 60));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setText("Log In as");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 120, 30));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setText("Password");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 120, 30));

        LoginEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LoginEmail.setForeground(new java.awt.Color(204, 204, 204));
        LoginEmail.setBorder(null);
        LoginEmail.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        LoginEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginEmailActionPerformed(evt);
            }
        });
        jPanel6.add(LoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 420, 40));

        jPanel13.setBackground(new java.awt.Color(223, 112, 0));
        jPanel13.setPreferredSize(new java.awt.Dimension(420, 2));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 420, -1));

        LoginPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginPassword.setForeground(new java.awt.Color(204, 204, 204));
        LoginPassword.setBorder(null);
        jPanel6.add(LoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 420, 40));

        LogInbtn.setBackground(new java.awt.Color(223, 112, 0));
        LogInbtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LogInbtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInbtn.setText("Log In");
        LogInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInbtnActionPerformed(evt);
            }
        });
        jPanel6.add(LogInbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 160, 50));

        ExitLogin.setBackground(new java.awt.Color(223, 112, 0));
        ExitLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ExitLogin.setForeground(new java.awt.Color(255, 255, 255));
        ExitLogin.setText("X");
        ExitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitLoginActionPerformed(evt);
            }
        });
        jPanel6.add(ExitLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 40, 30));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setText("Email");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 120, 30));

        UserType.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        UserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer", "Employee" }));
        UserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTypeActionPerformed(evt);
            }
        });
        jPanel6.add(UserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 120, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 670, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginEmailActionPerformed

    private void LogInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInbtnActionPerformed
    
        try{
            String url ="jdbc:sqlserver://ISHA\\SQLEXPRESS:1433;databaseName=ASAPCourier";
            String username = "asfiqun";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url,username,password);
            
            Statement statement = connection.createStatement();
            String UserPass1= String.valueOf(LoginPassword.getPassword());
            String AdminID= "admin@asap.org";
            String AdminPass="admin";
            
            
            if(UserType.getSelectedItem().equals("Admin")){
            if( LoginEmail.getText().equals(AdminID) && UserPass1.equals("admin"))
            {
            JOptionPane.showMessageDialog(this, "Successfully Logged In");
             new adminmenu2().setVisible(true);
            dispose();   
            }
            else{
            JOptionPane.showMessageDialog(this, "WRONG USER ID OR PASSWORD");
            }
            }
            else if(UserType.getSelectedItem().equals("Customer")){
            String sql1 = "select * from CUSTOMERINFO WHERE CustomerEmail='"+LoginEmail.getText()+"' AND CustomerPassword='"+UserPass1+"'";
            ResultSet rs = statement.executeQuery(sql1);
            if (rs.next()){
                String Customerid = String.valueOf(rs.getInt("CustomerId"));
                
                JOptionPane.showMessageDialog(this, "Successfully Logged In");
                new MainclassCustomer(Customerid).setVisible(true);
                dispose();  
            }
            else {
            JOptionPane.showMessageDialog(this, "WRONG USER ID OR PASSWORD");
            }
            }
            
            else if(UserType.getSelectedItem().equals("Employee")){
            String sql1 = "select * from employee WHERE employeemail='"+LoginEmail.getText()+"' AND employeepass='"+UserPass1+"'";
            ResultSet rs = statement.executeQuery(sql1);
            if (rs.next()){
                
                String Employeeid = String.valueOf(rs.getInt("employeeid"));
                JOptionPane.showMessageDialog(this, "Successfully Logged In");
                new employeemenu(Employeeid).setVisible(true);
                dispose();  
            }
            else {
            JOptionPane.showMessageDialog(this, "WRONG USER ID OR PASSWORD");
            }
            }

        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_LogInbtnActionPerformed

    private void ExitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitLoginActionPerformed
            System.exit(0);
    }//GEN-LAST:event_ExitLoginActionPerformed

    private void UserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTypeActionPerformed
        
    }//GEN-LAST:event_UserTypeActionPerformed

    private void RegisterPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPageActionPerformed
       Register register=new Register();
       register.setVisible(true);
       dispose();
    }//GEN-LAST:event_RegisterPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitLogin;
    private javax.swing.JButton LogInbtn;
    private javax.swing.JTextField LoginEmail;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JButton RegisterPage;
    private javax.swing.JComboBox<String> UserType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
